on: pull_request
name: PR Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Update permissions on mvnw
      run: chmod 700 mvnw
    - name: Package
      run: ./mvnw clean verify --no-transfer-progress
